{% set name = "chex" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chex-{{ version }}.tar.gz
  sha256: 686858320f8f220c82a6c7eeb54dcdcaa4f3d7f66690dacd13a24baa1ee8299e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - absl-py >=0.9.0
    - dm-tree >=0.1.5
    - jax >=0.1.55
    - jaxlib >=0.1.37
    - numpy >=1.18.0
    - toolz >=0.9.0

test:
  imports:
    - chex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepmind/chex
  summary: 'Chex: Testing made fun, in JAX!'
  description: |
    Chex is a library of utilities for helping to write reliable JAX code.

    This includes utils to help:

    - Instrument your code (e.g. assertions)
    - Debug (e.g. transforming pmaps in vmaps within a context manager).
    - Test JAX code across many variants (e.g. jitted vs non-jitted).
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/deepmind/chex
  doc_url: https://chex.readthedocs.io

extra:
  recipe-maintainers:
    - PhilipVinc
    - hbq1
