{% set name = "chex" %}
{% set version = "0.1.89" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chex-{{ version }}.tar.gz
  sha256: 78f856e6a0a8459edfcbb402c2c044d2b8102eac4b633838cbdfdcdb09c6c8e0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  # Matches jaxlib-feedstock's compatibility
  skip: true  # [s390x or py<310]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - absl-py >=0.9.0
    - dm-tree >=0.1.5
    - jax >=0.4.27
    - numpy >=1.24.1
    - toolz >=0.9.0
    - typing_extensions >=4.2.0
    - jaxlib >=0.4.27
    - setuptools  # [py>=312]

test:
  imports:
    - chex
  source_files:
    - chex
  requires:
    - pip
    - cloudpickle >=3,<3.2
    - pytest
  commands:
    - pip check
    - cd chex && pytest . -k "not fake_set_n_cpu_devices_test"

about:
  home: https://github.com/deepmind/chex
  summary: 'Chex: Testing made fun, in JAX!'
  description: |
    Chex is a library of utilities for helping to write reliable JAX code.

    This includes utils to help:

    - Instrument your code (e.g. assertions)
    - Debug (e.g. transforming pmaps in vmaps within a context manager).
    - Test JAX code across many variants (e.g. jitted vs non-jitted).
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/deepmind/chex
  doc_url: https://chex.readthedocs.io

extra:
  recipe-maintainers:
    - PhilipVinc
    - hbq1
  skip-lints:
    - missing_license_url
    - missing_doc_source_url
