{% set name = "chex" %}
{% set version = "0.1.91" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chex-{{ version }}.tar.gz
  sha256: 65367a521415ada905b8c0222b0a41a68337fcadf79a1fb6fc992dbd95dd9f76

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  # Matches jaxlib-feedstock's compatibility
  skip: true  # [py<311]

requirements:
  host:
    - pip
    - python
    - flit-core >=3.2,<4
  run:
    - python
    - absl-py >=2.3.1
    - typing_extensions >=4.15.0
    - jax >=0.7.0
    - jaxlib >=0.7.0
    - numpy >=1.24.1
    - toolz >=1.0.0

test:
  imports:
    - chex
  source_files:
    - chex
  requires:
    - pip
    - cloudpickle >=3,<3.2
    - pytest
  commands:
    - pip check
    - cd chex && pytest . -k "not fake_set_n_cpu_devices_test"  # [not win]
    # test_docstring_example fails with  AssertionError: Tree contains non-finite value: nan.
    - cd chex && pytest . -k "not (fake_set_n_cpu_devices_test or test_docstring_example)"  # [win]

about:
  home: https://github.com/deepmind/chex
  summary: "Chex: Testing made fun, in JAX!"
  description: |
    Chex is a library of utilities for helping to write reliable JAX code.

    This includes utils to help:

    - Instrument your code (e.g. assertions)
    - Debug (e.g. transforming pmaps in vmaps within a context manager).
    - Test JAX code across many variants (e.g. jitted vs non-jitted).
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/deepmind/chex
  doc_url: https://chex.readthedocs.io

extra:
  recipe-maintainers:
    - PhilipVinc
    - hbq1
  skip-lints:
    - missing_license_url
    - missing_doc_source_url
