{% set name = "chex" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chex-{{ version }}.tar.gz
  sha256: c490fdadc7153d41f00114d671b079e64dae68028465a936d59f1030bb38abe9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - absl-py >=0.9.0
    - dm-tree >=0.1.5
    - jax >=0.1.55
    - jaxlib >=0.1.37
    - numpy >=1.18.0
    - toolz >=0.9.0

test:
  imports:
    - chex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepmind/chex
  summary: 'Chex: Testing made fun, in JAX!'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PhilipVinc
    - hbq1
